### ISSUE TITLE
true-name-0.0.0.1 failing to build in stackage nightly ghc-7.10.2

### ISSUE THREAD

**Issue by juhp** [liyang/true-name#2]
true-name does not seem to build with ghc-7.10.2:

```
Configuring true-name-0.0.0.1...
Building true-name-0.0.0.1...
Preprocessing library true-name-0.0.0.1...
[1 of 1] Compiling Unsafe.TrueName  ( Unsafe/TrueName.hs, dist/build/Unsafe/TrueName.o )

Unsafe/TrueName.hs:59:5:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH.Syntax),
      ‘ClassI’ (imported from Language.Haskell.TH.Syntax),
      ‘Clause’ (imported from Language.Haskell.TH.Syntax)

Unsafe/TrueName.hs:60:5: Not in scope: data constructor ‘EqualP’
```

This was found while trying to build Stackage Nightly,
where true-name is getting pulled in as a benchmark dependency of the newly added fast-builder package.

cc @takano-akio

**Comment by takano-akio** [comment]
I've filed a pull request for this. https://github.com/liyang/true-name/pull/1

**Comment by juhp** [comment]
Thanks, Takano-san!

**Comment by liyang** [comment]
Um… I'm fashionably late to the party. Sorry.
